<!-- 頁尾 -->
<footer>
  <div id="footer-left">
    <ul>
      <li>
        2018 <a href="http://cs.chu.edu.tw/" target="_blank">中華大學資訊工程系</a> 資料探勘實驗室
      </li>
      <li>
        <ul>
          <li><a href="#" data-reveal-id="dev-people-modal">開發團隊</a></li>
          <li><a href="https://docs.google.com/forms/d/1SKVGoXXb_NdidF-C3ZNaqmFbWZdS_IXcfXITOZepAUQ/viewform?c=0&w=1" target="_blank">問題/意見回報</a></li>
          <li><a href="#" data-reveal-id="contact-me-modal">聯絡我們</a></li>
        </ul>
      </li>
    </ul>
</div>
  <div id="footer-right">
    <ul>
      <li>本網站建議使用<a href="https://www.google.com/chrome/browser/index.html" target="_blank">Google Chrome</a> 或 <a href="https://moztw.org/firefox/" target="_blank">Mozilla Firefox</a>瀏覽器</li>
      <li>Source:
        <ul>
          <li><a href="https://github.com/chu-dblab/Prediction-UI" target="_blank">Frontend</a></li>
          <li><a href="https://github.com/chu-dblab/GSAT_Prediction_API" target="_blank">Backend</a></li>
        </ul>
      </li>
    </ul>
  </div>
</footer>

<!-- 開發團隊 Dialog -->
<div id="dev-people-modal" class="reveal-modal" data-reveal>
  <div>
    <h2>開發團隊</h2>
    <div class="content">
      <ul>
        <li>指導教授：曾秋蓉</li>
        <li>前端程式：邱迺元/溫宏洋</li>
        <li>後端程式：林廣學</li>
        <li>資料收集：張修輔</li>
        <li>資料分析：邱孅平</li>
        <li>資料探勘：陳品甄</li>
        <li>資料整理：詹佳叡</li>
      </ul>
    </div>
    <a class="close-reveal-modal">&#215;</a>
  </div>
</div>

<!-- 聯絡我們 Dialog -->
<div id="contact-me-modal" class="reveal-modal" data-reveal>
  <div>
    <h2>聯絡我們</h2>
    <div class="content">
      <ul>
        <li>聯絡人: 中華大學資訊工程系曾秋蓉教授</li>
        <li>Email: <a href="mailto:judycrt@chu.edu.tw">judycrt@chu.edu.tw</a></li>
        <li>TEL: <a href="tel:0989090565">0989090565</a> / <a href="tel:035186383">03-5186383</a></li>
      </ul>
    </div>
    <a class="close-reveal-modal">&#215;</a>
  </div>
</div>
