<meta name="description" content="升大學該念什麼系？畢業後薪資又有多少？職涯型指考落點分析幫考生篩選最具錢景的校系。看薪資填志願，許你一個高薪的未來！107/2018指考落點分析/落點預測最佳選擇！">
<meta name="keywords" content="2018落點分析,落點分析,指考落點分析,指考落點預測,2018落點預測,107落點預測,107落點分析">
<meta property="og:site_name" content="升大學職涯型落點分析" />
<meta property="og:title" content="升大學職涯型落點分析" />
<meta property="og:image" content="images/screenshot.png"/>
<meta property="og:description" content="升大學該念什麼系？畢業後薪資又有多少？大學職涯分析服務 PK 給您看！" />
<meta property="og:url" content="http://predict.chu.edu.tw/" />
