<meta name="description" content="升大學該念什麼系？畢業後薪資又有多少？職涯型學測分科測驗落點分析幫考生篩選最具錢景的校系。看薪資填志願，許你一個高薪的未來！111/2022學測分科測驗落點分析/落點預測最佳選擇！">
<meta name="keywords" content="2022落點分析,111落點分析,落點分析,指考落點分析,分科測驗落點分析,學測落點分析,學測,指考,分科測驗,免費,推薦,落點預測,2022落點預測,111落點預測">
<meta property="og:site_name" content="升大學職涯型落點分析" />
<meta property="og:title" content="升大學職涯型落點分析" />
<meta property="og:image" content="https://predict.chu.edu.tw/2022/images/index.png"/>
<meta property="og:description" content="升大學該念什麼系？畢業後薪資又有多少？大學職涯分析服務 PK 給您看！" />
<meta property="og:url" content="https://predict.chu.edu.tw/2022/" />
